name: Release

on:
  push:
    branches:
      - main

jobs:
  rollout_migration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn install
      - run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      - run: echo "DIRECT_URL=${{ secrets.DATABASE_URL }}" >> .env
      - run: yarn prisma migrate deploy

